### ISSUE TITLE
First Settings 

### ISSUE THREAD

**Issue by Meith0717** [Meith0717/Stellar-Liberation#45]
## Wanted
- [x] Music Volume Slider
- [x] Sound Effects Volume Slider
- [x] Screen Size Setting 
- [x] Apply Button Setting

## To-do
- [x] #49
